// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebApplication2.todo {
	
	
	public partial class WebForm1 {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.Panel tagOut;
		
		protected AjaxControlToolkit.DynamicPopulateExtender dpop;
	}
}
